
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module VGA_P3(

	//////////// CLOCK //////////
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,
	input 		          		CLOCK4_50,
	input 		          		CLOCK_50,

	//////////// SEG7 //////////
	/*output	reg	     [6:0]		HEX0,
	output	reg	     [6:0]		HEX1,
	output	reg	     [6:0]		HEX2,
	output	reg	     [6:0]		HEX3,
	output	reg	     [6:0]		HEX4,
	output	reg	     [6:0]		HEX5,
	*/
	//////////// KEY //////////
	input 		     [3:0]		KEY,

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// SW //////////
	input 		     [9:0]		SW,

	//////////// VGA //////////
	output		          			VGA_BLANK_N,
	output		reg     [7:0]		VGA_B,
	output		          			VGA_CLK,
	output		reg     [7:0]		VGA_G,
	output		    	      		VGA_HS,
	output		reg     [7:0]		VGA_R,
	output		        	  			VGA_SYNC_N,
	output		          			VGA_VS
);

//=======================================================
//  PARAMETER declarations
//=======================================================

//	Horizontal Parameter	( Pixel )
parameter	H_SYNC_CYC	=	96;
parameter	H_SYNC_BACK	=	48;
parameter	H_SYNC_ACT	=	640;
parameter	H_SYNC_FRONT=	16;
parameter	H_SYNC_TOTAL=	800;

//	Virtical Parameter		( Line )
parameter	V_SYNC_CYC	=	2;
parameter	V_SYNC_BACK	=	33;
parameter	V_SYNC_ACT	=	480;
parameter	V_SYNC_FRONT=	10;
parameter	V_SYNC_TOTAL=	525;
//	Start Offset
parameter	X_START		=	H_SYNC_CYC+H_SYNC_BACK;
parameter	Y_START		=	V_SYNC_CYC+V_SYNC_BACK;




//=======================================================
//  REG/WIRE declarations
//=======================================================
wire CLOCK_25;
wire iStart_n = SW[9];

wire en_hs;
wire en_vs;
wire en;


reg reset = 1'b0;

//	Internal Registers and Wires
reg		[11:0]		H_Cont = 12'b0;
reg		[11:0]		V_Cont = 12'b0;
reg     [11:0]		en_cnt = 12'b0;

reg [255:0]cnt_hs;
reg [255:0]cnt_vs;
reg [23:0]oRGB;
reg vga_hs;
reg vga_vs;


reg [7:0]R;
reg[7:0]G;
reg[7:0]B;

// reg[23:0]en_cnt;

reg enable;

wire book;
wire data_en;
wire H_wire;
wire V_wire;

//=======================================================
//  Structural coding
//=======================================================
assign VGA_BLANK_N = data_en;
assign VGA_SYNC_N = 1'b0;
assign VGA_CLK = CLOCK_25;


input_badge u_input_badge(
	.iStart_n(SW[7]),
	.iCLK(CLOCK_25),
	.iRST_N(SW[8]),

	.oData_Enable(data_en),
	.oData(oRGB),
	.HSYNC(H_wire),
	.VSYNC(V_wire)
);

PLL_25 u1(
		.refclk(CLOCK_50),   //  refclk.clk
		.rst(reset),      //   reset.reset
		.outclk_0(CLOCK_25), // outclk0.clk
		.locked()    //  locked.export
	);


assign VGA_HS = H_wire;
assign VGA_VS = V_wire;
	
	


always@(posedge CLOCK_25 or negedge KEY[3])begin
	if(!KEY[3])begin
		cnt_hs <= 0;
	end
	else begin
		if(data_en && cnt_hs < 640)begin
			cnt_hs <= cnt_hs + 1;
		end
		else if(cnt_hs == 640)begin
			cnt_hs <= 0;
		end
		else begin
			cnt_hs <= cnt_hs;
		end
	end
end


always@(posedge CLOCK_25 or negedge KEY[3])begin
	if(!KEY[3])begin
		cnt_vs <= 0;
	end
	else begin
		if( cnt_hs ==640 && cnt_vs < 480)begin
				cnt_vs <= cnt_vs + 1;
		end
		else if(cnt_vs ==480)begin
				cnt_vs <= 0;
		end
		else begin
			cnt_vs <= cnt_vs;
		end
	end	
end


assign book = (cnt_vs>=197)&&(cnt_vs<207)&&(cnt_hs>=203)&&(cnt_hs<249);
//(cnt_hs>=203)&&(cnt_hs<249)
//(cnt_vs>=197)&&(cnt_vs<207)

always @ (posedge CLOCK_25 or negedge KEY[1])
		if (!KEY[1])
			{VGA_B,VGA_G,VGA_R} <= 24'd0;
		else
			if(book&&SW[0])begin
					{VGA_B,VGA_G,VGA_R} <= 24'hffffff;
			end
			else if(data_en==1'b1)
					{VGA_B,VGA_G,VGA_R} <= oRGB;
								
			else
				{VGA_B,VGA_G,VGA_R} <= 24'h0;



endmodule
